apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: key-protect-test-pipeline
  description: A test pipeline for using key protect in tekton properties
spec:
  params:
    - name: key-protect-apikey
      description: api key property
    - name: key-protect-endpoint
      description: ibmcloud endpoint
  tasks:
    - name: key-protect
      taskRef:
        name: key-protect
      params:
        - name: key-protect-apikey
          value: $(params.key-protect-apikey)
        - name: key-protect-endpoint
          value: $(params.key-protect-endpoint)
