apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: key-protect-test-pipeline
spec:
  params:
    - name: key_protect_apikey
      description: api key property
  tasks:
    - name: key-protect
      taskRef:
        name: key-protect
      params:
        - name: key_protect_apikey
          value: $(params.key_protect_apikey)
