apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: key-protect
spec:
  params:
    - name: key-protect-apikey
      description: api key property
  steps:
    - name: key-protect-test
      image: ibmcom/pipeline-base-image:2.9
      env:
        - name: key-protect-apikey
          value: $(params.key-protect-apikey)
      command: ["bash", "-c"]
      args:
        - |
          #!/usr/bin/env bash
          echo "Key Protect Test"
          echo "================"
          echo "apikey: ${key-protect-apikey}"
          ibmcloud login --apikey ${key-protect-apikey} --no-region
