apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: key-protect
spec:
  params:
    - name: e2e_key_protect_api_key
      description: api key property
  steps:
    - name: key-protect-test
      image: ibmcom/pipeline-base-image:2.9
      env:
        - name: E2E_KEY_PROTECT_API_KEY
          value: $(inputs.params.e2e_key_protect_api_key)
      command: ["bash", "-c"]
      args:
        - |
          #!/usr/bin/env bash
          echo "Key Protect Test"
          echo "================"
          ibmcloud login --apikey ${E2E_KEY_PROTECT_API_KEY} --no-region
